# Generated by Django 4.1.3 on 2024-09-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdffile",
            name="name",
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name="pdffile",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
